### ISSUE TITLE
[Bug] Cannot install mvn project

### ISSUE THREAD

**Issue by anidem210** [salesforce/utam-java-recipes#16]
### Actual behavior

![image](https://user-images.githubusercontent.com/52797477/153274094-a326b3ba-02e8-4bc5-be65-9fa8f2a56e59.png)
![image](https://user-images.githubusercontent.com/52797477/153273685-556d099d-4ff6-4416-a524-208913e5bfb4.png)

- [x] Unable to compile a Page Object

- [ ] Invalid generated code

- [ ] Runtime error

### What is your expected behavior?

There should be no errors in the maven install, either in the terminal or in eclipse.
### Steps to reproduce

Just follow the initial setup of the readme.md:
git clone https://github.com/salesforce/utam-java-recipes.git
cd utam-java-recipes
mvn clean install
### Environment

Apache Maven 3.8.2 
java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional context

Eclipse importing issue:
![image](https://user-images.githubusercontent.com/52797477/153275405-28f93d82-9062-44ed-b8ff-622362598ef1.png)

**Comment by jimevanssfdc** [comment]
@anidem210 This looks like an issue with the UTAM Java compiler. Thank you for bringing it to our attention. We'll try to get it figured out and fixed as soon as we can.

**Comment by jimevanssfdc** [comment]
@anidem210 We have identified the issue in the UTAM Java compiler and it is fixed in version `1.0.5` of the same. A PR has been opened to update to the fixed version of the compiler, and once merged, this issue should be resolved.
