### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by girish-kadambari** [salesforce/utam-java-recipes#41]
### Actual behavior

- [x] Unable to compile a Page Object

- [ ] Invalid generated code

- [ ] Runtime error

### What is your expected behavior?

After following the instrucations given in this doc . I'm getting error with Classes not found like examples 
import utam.tests.pageobjects.UtamChild;
import utam.tests.pageobjects.UtamParent;
Need to remove those classess

There is not doc for this class 
UtamDevHome

**Comment by kartikperumal** [comment]
Hi @girish-kadambari , Could you please post the exact steps you have followed and the error message?

**Comment by irinash13** [comment]
Closing with no response
